server:
  port: 6001


spring:
  datasource:
    dspdb:
      jdbc-url: jdbc:mysql://10.72.3.168:3310/${db}?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
      username: wjw
      password: wjw@123
      driver-class-name: com.mysql.jdbc.Driver
      initialSize: 10
      minIdle: 5
      maxActive: 100
      maxWait: 60000

      filter:
        stat:
          enabled: true
        wall:
          enabled: true
          drop-table-allow: false
          config:
            multi-statement-allow: true
  redis:
    password: bjSogal
    timeout: 15
    sentinel:
      master: mymaster
      nodes: 10.72.1.67:26379
    pool:
      max-active: 13
      max-idle: 1
      min-idle: 11
      max-wait: 11
    pool0: 1
    pool1: 2
    pool2: 3

db: dspdb

