server:
  port: 6001


spring:
  redis:
    password: bjSogal
    timeout: 15
    sentinel:
      master: mymaster
      nodes: 10.72.1.67:26379,10.72.1.68:26379,10.72.1.69:26379
    pool:
      max-active: 13
      max-idle: 1
      min-idle: 11
      max-wait: 11
    pool0: 1
    pool1: 2
    pool2: 3

